let maplocalleader=" "

set spelllang=pt_br

nnoremap <localleader><localleader> :set spell!<cr>
nnoremap <localleader>n ]s
nnoremap <localleader>N [s
nnoremap <localleader>b 1z=
nnoremap <localleader>gf I<esc>f(lgf

"modified unicodef (github.com/tsouanas/unicodef)
abbrev <buffer> bomb 💣
abbrev <buffer> boom 💥
abbrev <buffer> bulb 💡
abbrev <buffer> hrmf ⍨
abbrev <buffer> pirate ☠
abbrev <buffer> poo 💩
abbrev <buffer> smooch ⍣
abbrev <buffer> zzz 💤
abbrev <buffer> tada 🎉
abbrev <buffer> scrA 𝒜
abbrev <buffer> scrB ℬ
abbrev <buffer> scrC 𝒞
abbrev <buffer> scrD 𝒟
abbrev <buffer> scrE ℰ
abbrev <buffer> scrF ℱ
abbrev <buffer> scrG 𝒢
abbrev <buffer> scrH ℋ
abbrev <buffer> scrI ℐ
abbrev <buffer> scrJ 𝒥
abbrev <buffer> scrK 𝒦
abbrev <buffer> scrL ℒ
abbrev <buffer> scrM ℳ
abbrev <buffer> scrN 𝒩
abbrev <buffer> scrO 𝒪
abbrev <buffer> scrP 𝒫
abbrev <buffer> scrQ 𝒬
abbrev <buffer> scrR ℛ
abbrev <buffer> scrS 𝒮
abbrev <buffer> scrT 𝒯
abbrev <buffer> scrU 𝒰
abbrev <buffer> scrV 𝒱
abbrev <buffer> scrW 𝒲
abbrev <buffer> scrX 𝒳
abbrev <buffer> scrY 𝒴
abbrev <buffer> scrZ 𝒵
abbrev <buffer> scra 𝒶
abbrev <buffer> scrb 𝒷
abbrev <buffer> scrc 𝒸
abbrev <buffer> scrd 𝒹
abbrev <buffer> scre ℯ
abbrev <buffer> scrf 𝒻
abbrev <buffer> scrg ℊ
abbrev <buffer> scrh 𝒽
abbrev <buffer> scri 𝒾
abbrev <buffer> scrj 𝒿
abbrev <buffer> scrk 𝓀
abbrev <buffer> scrl 𝓁
abbrev <buffer> scrm 𝓂
abbrev <buffer> scrn 𝓃
abbrev <buffer> scro ℴ
abbrev <buffer> scrp 𝓅
abbrev <buffer> scrq 𝓆
abbrev <buffer> scrr 𝓇
abbrev <buffer> scrs 𝓈
abbrev <buffer> scrt 𝓉
abbrev <buffer> scru 𝓊
abbrev <buffer> scrv 𝓋
abbrev <buffer> scrw 𝓌
abbrev <buffer> scrx 𝓍
abbrev <buffer> scry 𝓎
abbrev <buffer> scrz 𝓏
abbrev <buffer> calA 𝓐
abbrev <buffer> calB 𝓑
abbrev <buffer> calC 𝓒
abbrev <buffer> calD 𝓓
abbrev <buffer> calE 𝓔
abbrev <buffer> calF 𝓕
abbrev <buffer> calG 𝓖
abbrev <buffer> calH 𝓗
abbrev <buffer> calI 𝓘
abbrev <buffer> calJ 𝓙
abbrev <buffer> calK 𝓚
abbrev <buffer> calL 𝓛
abbrev <buffer> calM 𝓜
abbrev <buffer> calN 𝓝
abbrev <buffer> calO 𝓞
abbrev <buffer> calP 𝓟
abbrev <buffer> calQ 𝓠
abbrev <buffer> calR 𝓡
abbrev <buffer> calS 𝓢
abbrev <buffer> calT 𝓣
abbrev <buffer> calU 𝓤
abbrev <buffer> calV 𝓥
abbrev <buffer> calW 𝓦
abbrev <buffer> calX 𝓧
abbrev <buffer> calY 𝓨
abbrev <buffer> calZ 𝓩
abbrev <buffer> cala 𝓪
abbrev <buffer> calb 𝓫
abbrev <buffer> calc 𝓬
abbrev <buffer> cald 𝓭
abbrev <buffer> cale 𝓮
abbrev <buffer> calf 𝓯
abbrev <buffer> calg 𝓰
abbrev <buffer> calh 𝓱
abbrev <buffer> cali 𝓲
abbrev <buffer> calj 𝓳
abbrev <buffer> calk 𝓴
abbrev <buffer> call 𝓵
abbrev <buffer> calm 𝓶
abbrev <buffer> caln 𝓷
abbrev <buffer> calo 𝓸
abbrev <buffer> calp 𝓹
abbrev <buffer> calq 𝓺
abbrev <buffer> calr 𝓻
abbrev <buffer> cals 𝓼
abbrev <buffer> calt 𝓽
abbrev <buffer> calu 𝓾
abbrev <buffer> calv 𝓿
abbrev <buffer> calw 𝔀
abbrev <buffer> calx 𝔁
abbrev <buffer> caly 𝔂
abbrev <buffer> calz 𝔃
abbrev <buffer> ttA 𝙰
abbrev <buffer> ttB 𝙱
abbrev <buffer> ttC 𝙲
abbrev <buffer> ttD 𝙳
abbrev <buffer> ttE 𝙴
abbrev <buffer> ttF 𝙵
abbrev <buffer> ttG 𝙶
abbrev <buffer> ttH 𝙷
abbrev <buffer> ttI 𝙸
abbrev <buffer> ttJ 𝙹
abbrev <buffer> ttK 𝙺
abbrev <buffer> ttL 𝙻
abbrev <buffer> ttM 𝙼
abbrev <buffer> ttN 𝙽
abbrev <buffer> ttO 𝙾
abbrev <buffer> ttP 𝙿
abbrev <buffer> ttQ 𝚀
abbrev <buffer> ttR 𝚁
abbrev <buffer> ttS 𝚂
abbrev <buffer> ttT 𝚃
abbrev <buffer> ttU 𝚄
abbrev <buffer> ttV 𝚅
abbrev <buffer> ttW 𝚆
abbrev <buffer> ttX 𝚇
abbrev <buffer> ttY 𝚈
abbrev <buffer> ttZ 𝚉
abbrev <buffer> tta 𝚊
abbrev <buffer> ttb 𝚋
abbrev <buffer> ttc 𝚌
abbrev <buffer> ttd 𝚍
abbrev <buffer> tte 𝚎
abbrev <buffer> ttf 𝚏
abbrev <buffer> ttg 𝚐
abbrev <buffer> tth 𝚑
abbrev <buffer> tti 𝚒
abbrev <buffer> ttj 𝚓
abbrev <buffer> ttk 𝚔
abbrev <buffer> ttl 𝚕
abbrev <buffer> ttm 𝚖
abbrev <buffer> ttn 𝚗
abbrev <buffer> tto 𝚘
abbrev <buffer> ttp 𝚙
abbrev <buffer> ttq 𝚚
abbrev <buffer> ttr 𝚛
abbrev <buffer> tts 𝚜
abbrev <buffer> ttt 𝚝
abbrev <buffer> ttu 𝚞
abbrev <buffer> ttv 𝚟
abbrev <buffer> ttw 𝚠
abbrev <buffer> ttx 𝚡
abbrev <buffer> tty 𝚢
abbrev <buffer> ttz 𝚣
abbrev <buffer> itA 𝐴
abbrev <buffer> itB 𝐵
abbrev <buffer> itC 𝐶
abbrev <buffer> itD 𝐷
abbrev <buffer> itE 𝐸
abbrev <buffer> itF 𝐹
abbrev <buffer> itG 𝐺
abbrev <buffer> itH 𝐻
abbrev <buffer> itI 𝐼
abbrev <buffer> itJ 𝐽
abbrev <buffer> itK 𝐾
abbrev <buffer> itL 𝐿
abbrev <buffer> itM 𝑀
abbrev <buffer> itN 𝑁
abbrev <buffer> itO 𝑂
abbrev <buffer> itP 𝑃
abbrev <buffer> itQ 𝑄
abbrev <buffer> itR 𝑅
abbrev <buffer> itS 𝑆
abbrev <buffer> itT 𝑇
abbrev <buffer> itU 𝑈
abbrev <buffer> itV 𝑉
abbrev <buffer> itW 𝑊
abbrev <buffer> itX 𝑋
abbrev <buffer> itY 𝑌
abbrev <buffer> itZ 𝑍
abbrev <buffer> ita 𝑎
abbrev <buffer> itb 𝑏
abbrev <buffer> itc 𝑐
abbrev <buffer> itd 𝑑
abbrev <buffer> ite 𝑒
abbrev <buffer> itf 𝑓
abbrev <buffer> itg 𝑔
abbrev <buffer> ith ℎ
abbrev <buffer> iti 𝑖
abbrev <buffer> itj 𝑗
abbrev <buffer> itk 𝑘
abbrev <buffer> itl 𝑙
abbrev <buffer> itm 𝑚
abbrev <buffer> itn 𝑛
abbrev <buffer> ito 𝑜
abbrev <buffer> itp 𝑝
abbrev <buffer> itq 𝑞
abbrev <buffer> itr 𝑟
abbrev <buffer> its 𝑠
abbrev <buffer> itt 𝑡
abbrev <buffer> itu 𝑢
abbrev <buffer> itv 𝑣
abbrev <buffer> itw 𝑤
abbrev <buffer> itx 𝑥
abbrev <buffer> ity 𝑦
abbrev <buffer> itz 𝑧
abbrev <buffer> isA 𝘈
abbrev <buffer> isB 𝘉
abbrev <buffer> isC 𝘊
abbrev <buffer> isD 𝘋
abbrev <buffer> isE 𝘌
abbrev <buffer> isF 𝘍
abbrev <buffer> isG 𝘎
abbrev <buffer> isH 𝘏
abbrev <buffer> isI 𝘐
abbrev <buffer> isJ 𝘑
abbrev <buffer> isK 𝘒
abbrev <buffer> isL 𝘓
abbrev <buffer> isM 𝘔
abbrev <buffer> isN 𝘕
abbrev <buffer> isO 𝘖
abbrev <buffer> isP 𝘗
abbrev <buffer> isQ 𝘘
abbrev <buffer> isR 𝘙
abbrev <buffer> isS 𝘚
abbrev <buffer> isT 𝘛
abbrev <buffer> isU 𝘜
abbrev <buffer> isV 𝘝
abbrev <buffer> isW 𝘞
abbrev <buffer> isX 𝘟
abbrev <buffer> isY 𝘠
abbrev <buffer> isZ 𝘡
abbrev <buffer> isa 𝘢
abbrev <buffer> isb 𝘣
abbrev <buffer> isc 𝘤
abbrev <buffer> isd 𝘥
abbrev <buffer> ise 𝘦
abbrev <buffer> isf 𝘧
abbrev <buffer> isg 𝘨
abbrev <buffer> ish 𝘩
abbrev <buffer> isi 𝘪
abbrev <buffer> isj 𝘫
abbrev <buffer> isk 𝘬
abbrev <buffer> isl 𝘭
abbrev <buffer> ism 𝘮
abbrev <buffer> isn 𝘯
abbrev <buffer> iso 𝘰
abbrev <buffer> isp 𝘱
abbrev <buffer> isq 𝘲
abbrev <buffer> isr 𝘳
abbrev <buffer> iss 𝘴
abbrev <buffer> ist 𝘵
abbrev <buffer> isu 𝘶
abbrev <buffer> isv 𝘷
abbrev <buffer> isw 𝘸
abbrev <buffer> isx 𝘹
abbrev <buffer> isy 𝘺
abbrev <buffer> isz 𝘻
abbrev <buffer> bfA 𝐀
abbrev <buffer> bfB 𝐁
abbrev <buffer> bfC 𝐂
abbrev <buffer> bfD 𝐃
abbrev <buffer> bfE 𝐄
abbrev <buffer> bfF 𝐅
abbrev <buffer> bfG 𝐆
abbrev <buffer> bfH 𝐇
abbrev <buffer> bfI 𝐈
abbrev <buffer> bfJ 𝐉
abbrev <buffer> bfK 𝐊
abbrev <buffer> bfL 𝐋
abbrev <buffer> bfM 𝐌
abbrev <buffer> bfN 𝐍
abbrev <buffer> bfO 𝐎
abbrev <buffer> bfP 𝐏
abbrev <buffer> bfQ 𝐐
abbrev <buffer> bfR 𝐑
abbrev <buffer> bfS 𝐒
abbrev <buffer> bfT 𝐓
abbrev <buffer> bfU 𝐔
abbrev <buffer> bfV 𝐕
abbrev <buffer> bfW 𝐖
abbrev <buffer> bfX 𝐗
abbrev <buffer> bfY 𝐘
abbrev <buffer> bfZ 𝐙
abbrev <buffer> bfa 𝐚
abbrev <buffer> bfb 𝐛
abbrev <buffer> bfc 𝐜
abbrev <buffer> bfd 𝐝
abbrev <buffer> bfe 𝐞
abbrev <buffer> bff 𝐟
abbrev <buffer> bfg 𝐠
abbrev <buffer> bfh 𝐡
abbrev <buffer> bfi 𝐢
abbrev <buffer> bfj 𝐣
abbrev <buffer> bfk 𝐤
abbrev <buffer> bfl 𝐥
abbrev <buffer> bfm 𝐦
abbrev <buffer> bfn 𝐧
abbrev <buffer> bfo 𝐨
abbrev <buffer> bfp 𝐩
abbrev <buffer> bfq 𝐪
abbrev <buffer> bfr 𝐫
abbrev <buffer> bfs 𝐬
abbrev <buffer> bft 𝐭
abbrev <buffer> bfu 𝐮
abbrev <buffer> bfv 𝐯
abbrev <buffer> bfw 𝐰
abbrev <buffer> bfx 𝐱
abbrev <buffer> bfy 𝐲
abbrev <buffer> bfz 𝐳
abbrev <buffer> bf1 𝟎
abbrev <buffer> bf2 𝟏
abbrev <buffer> bf3 𝟐
abbrev <buffer> bf4 𝟑
abbrev <buffer> bf5 𝟒
abbrev <buffer> bf6 𝟓
abbrev <buffer> bf7 𝟔
abbrev <buffer> bf8 𝟕
abbrev <buffer> bf9 𝟖
abbrev <buffer> bf10 𝟗
abbrev <buffer> bfiA 𝑨
abbrev <buffer> bfiB 𝑩
abbrev <buffer> bfiC 𝑪
abbrev <buffer> bfiD 𝑫
abbrev <buffer> bfiE 𝑬
abbrev <buffer> bfiF 𝑭
abbrev <buffer> bfiG 𝑮
abbrev <buffer> bfiH 𝑯
abbrev <buffer> bfiI 𝑰
abbrev <buffer> bfiJ 𝑱
abbrev <buffer> bfiK 𝑲
abbrev <buffer> bfiL 𝑳
abbrev <buffer> bfiM 𝑴
abbrev <buffer> bfiN 𝑵
abbrev <buffer> bfiO 𝑶
abbrev <buffer> bfiP 𝑷
abbrev <buffer> bfiQ 𝑸
abbrev <buffer> bfiR 𝑹
abbrev <buffer> bfiS 𝑺
abbrev <buffer> bfiT 𝑻
abbrev <buffer> bfiU 𝑼
abbrev <buffer> bfiV 𝑽
abbrev <buffer> bfiW 𝑾
abbrev <buffer> bfiX 𝑿
abbrev <buffer> bfiY 𝒀
abbrev <buffer> bfiZ 𝒁
abbrev <buffer> bfia 𝒂
abbrev <buffer> bfib 𝒃
abbrev <buffer> bfic 𝒄
abbrev <buffer> bfid 𝒅
abbrev <buffer> bfie 𝒆
abbrev <buffer> bfif 𝒇
abbrev <buffer> bfig 𝒈
abbrev <buffer> bfih 𝒉
abbrev <buffer> bfii 𝒊
abbrev <buffer> bfij 𝒋
abbrev <buffer> bfik 𝒌
abbrev <buffer> bfil 𝒍
abbrev <buffer> bfim 𝒎
abbrev <buffer> bfin 𝒏
abbrev <buffer> bfio 𝒐
abbrev <buffer> bfip 𝒑
abbrev <buffer> bfiq 𝒒
abbrev <buffer> bfir 𝒓
abbrev <buffer> bfis 𝒔
abbrev <buffer> bfit 𝒕
abbrev <buffer> bfiu 𝒖
abbrev <buffer> bfiv 𝒗
abbrev <buffer> bfiw 𝒘
abbrev <buffer> bfix 𝒙
abbrev <buffer> bfiy 𝒚
abbrev <buffer> bfiz 𝒛
abbrev <buffer> bsA 𝗔
abbrev <buffer> bsB 𝗕
abbrev <buffer> bsC 𝗖
abbrev <buffer> bsD 𝗗
abbrev <buffer> bsE 𝗘
abbrev <buffer> bsF 𝗙
abbrev <buffer> bsG 𝗚
abbrev <buffer> bsH 𝗛
abbrev <buffer> bsI 𝗜
abbrev <buffer> bsJ 𝗝
abbrev <buffer> bsK 𝗞
abbrev <buffer> bsL 𝗟
abbrev <buffer> bsM 𝗠
abbrev <buffer> bsN 𝗡
abbrev <buffer> bsO 𝗢
abbrev <buffer> bsP 𝗣
abbrev <buffer> bsQ 𝗤
abbrev <buffer> bsR 𝗥
abbrev <buffer> bsS 𝗦
abbrev <buffer> bsT 𝗧
abbrev <buffer> bsU 𝗨
abbrev <buffer> bsV 𝗩
abbrev <buffer> bsW 𝗪
abbrev <buffer> bsX 𝗫
abbrev <buffer> bsY 𝗬
abbrev <buffer> bsZ 𝗭
abbrev <buffer> bsa 𝗮
abbrev <buffer> bsb 𝗯
abbrev <buffer> bsc 𝗰
abbrev <buffer> bsd 𝗱
abbrev <buffer> bse 𝗲
abbrev <buffer> bsf 𝗳
abbrev <buffer> bsg 𝗴
abbrev <buffer> bsh 𝗵
abbrev <buffer> bsi 𝗶
abbrev <buffer> bsj 𝗷
abbrev <buffer> bsk 𝗸
abbrev <buffer> bsl 𝗹
abbrev <buffer> bsm 𝗺
abbrev <buffer> bsn 𝗻
abbrev <buffer> bso 𝗼
abbrev <buffer> bsp 𝗽
abbrev <buffer> bsq 𝗾
abbrev <buffer> bsr 𝗿
abbrev <buffer> bss 𝘀
abbrev <buffer> bst 𝘁
abbrev <buffer> bsu 𝘂
abbrev <buffer> bsv 𝘃
abbrev <buffer> bsw 𝘄
abbrev <buffer> bsx 𝘅
abbrev <buffer> bsy 𝘆
abbrev <buffer> bsz 𝘇
abbrev <buffer> bs1 𝟬
abbrev <buffer> bs2 𝟭
abbrev <buffer> bs3 𝟮
abbrev <buffer> bs4 𝟯
abbrev <buffer> bs5 𝟰
abbrev <buffer> bs6 𝟱
abbrev <buffer> bs7 𝟲
abbrev <buffer> bs8 𝟳
abbrev <buffer> bs9 𝟴
abbrev <buffer> bs10 𝟵
abbrev <buffer> bsiA 𝘼
abbrev <buffer> bsiB 𝘽
abbrev <buffer> bsiC 𝘾
abbrev <buffer> bsiD 𝘿
abbrev <buffer> bsiE 𝙀
abbrev <buffer> bsiF 𝙁
abbrev <buffer> bsiG 𝙂
abbrev <buffer> bsiH 𝙃
abbrev <buffer> bsiI 𝙄
abbrev <buffer> bsiJ 𝙅
abbrev <buffer> bsiK 𝙆
abbrev <buffer> bsiL 𝙇
abbrev <buffer> bsiM 𝙈
abbrev <buffer> bsiN 𝙉
abbrev <buffer> bsiO 𝙊
abbrev <buffer> bsiP 𝙋
abbrev <buffer> bsiQ 𝙌
abbrev <buffer> bsiR 𝙍
abbrev <buffer> bsiS 𝙎
abbrev <buffer> bsiT 𝙏
abbrev <buffer> bsiU 𝙐
abbrev <buffer> bsiV 𝙑
abbrev <buffer> bsiW 𝙒
abbrev <buffer> bsiX 𝙓
abbrev <buffer> bsiY 𝙔
abbrev <buffer> bsiZ 𝙕
abbrev <buffer> bsia 𝙖
abbrev <buffer> bsib 𝙗
abbrev <buffer> bsic 𝙘
abbrev <buffer> bsid 𝙙
abbrev <buffer> bsie 𝙚
abbrev <buffer> bsif 𝙛
abbrev <buffer> bsig 𝙜
abbrev <buffer> bsih 𝙝
abbrev <buffer> bsii 𝙞
abbrev <buffer> bsij 𝙟
abbrev <buffer> bsik 𝙠
abbrev <buffer> bsil 𝙡
abbrev <buffer> bsim 𝙢
abbrev <buffer> bsin 𝙣
abbrev <buffer> bsio 𝙤
abbrev <buffer> bsip 𝙥
abbrev <buffer> bsiq 𝙦
abbrev <buffer> bsir 𝙧
abbrev <buffer> bsis 𝙨
abbrev <buffer> bsit 𝙩
abbrev <buffer> bsiu 𝙪
abbrev <buffer> bsiv 𝙫
abbrev <buffer> bsiw 𝙬
abbrev <buffer> bsix 𝙭
abbrev <buffer> bsiy 𝙮
abbrev <buffer> bsiz 𝙯
abbrev <buffer> bbA 𝔸
abbrev <buffer> bbB 𝔹
abbrev <buffer> bbC ℂ
abbrev <buffer> bbD 𝔻
abbrev <buffer> bbE 𝔼
abbrev <buffer> bbF 𝔽
abbrev <buffer> bbG 𝔾
abbrev <buffer> bbH ℍ
abbrev <buffer> bbI 𝕀
abbrev <buffer> bbJ 𝕁
abbrev <buffer> bbK 𝕂
abbrev <buffer> bbL 𝕃
abbrev <buffer> bbM 𝕄
abbrev <buffer> bbN ℕ
abbrev <buffer> bbO 𝕆
abbrev <buffer> bbP ℙ
abbrev <buffer> bbQ ℚ
abbrev <buffer> bbR ℝ
abbrev <buffer> bbS 𝕊
abbrev <buffer> bbT 𝕋
abbrev <buffer> bbU 𝕌
abbrev <buffer> bbV 𝕍
abbrev <buffer> bbW 𝕎
abbrev <buffer> bbX 𝕏
abbrev <buffer> bbY 𝕐
abbrev <buffer> bbZ ℤ
abbrev <buffer> bba 𝕒
abbrev <buffer> bbb 𝕓
abbrev <buffer> bbc 𝕔
abbrev <buffer> bbd 𝕕
abbrev <buffer> bbe 𝕖
abbrev <buffer> bbf 𝕗
abbrev <buffer> bbg 𝕘
abbrev <buffer> bbh 𝕙
abbrev <buffer> bbi 𝕚
abbrev <buffer> bbj 𝕛
abbrev <buffer> bbk 𝕜
abbrev <buffer> bbl 𝕝
abbrev <buffer> bbm 𝕞
abbrev <buffer> bbn 𝕟
abbrev <buffer> bbo 𝕠
abbrev <buffer> bbp 𝕡
abbrev <buffer> bbq 𝕢
abbrev <buffer> bbr 𝕣
abbrev <buffer> bbs 𝕤
abbrev <buffer> bbt 𝕥
abbrev <buffer> bbu 𝕦
abbrev <buffer> bbv 𝕧
abbrev <buffer> bbw 𝕨
abbrev <buffer> bbx 𝕩
abbrev <buffer> bby 𝕪
abbrev <buffer> bbz 𝕫
abbrev <buffer> bb1 𝟘
abbrev <buffer> bb2 𝟙
abbrev <buffer> bb3 𝟚
abbrev <buffer> bb4 𝟛
abbrev <buffer> bb5 𝟜
abbrev <buffer> bb6 𝟝
abbrev <buffer> bb7 𝟞
abbrev <buffer> bb8 𝟟
abbrev <buffer> bb9 𝟠
abbrev <buffer> bb10 𝟡
abbrev <buffer> bbiD ⅅ
abbrev <buffer> bbid ⅆ
abbrev <buffer> bbie ⅇ
abbrev <buffer> bbii ⅈ
abbrev <buffer> bbij ⅉ
abbrev <buffer> bbGam ℾ
abbrev <buffer> bbPi ℿ
abbrev <buffer> bbSig ⅀
abbrev <buffer> bbgam ℽ
abbrev <buffer> bbpi ℼ
abbrev <buffer> frakA 𝔄
abbrev <buffer> frakB 𝔅
abbrev <buffer> frakC ℭ
abbrev <buffer> frakD 𝔇
abbrev <buffer> frakE 𝔈
abbrev <buffer> frakF 𝔉
abbrev <buffer> frakG 𝔊
abbrev <buffer> frakH ℌ
abbrev <buffer> frakI ℑ
abbrev <buffer> frakJ 𝔍
abbrev <buffer> frakK 𝔎
abbrev <buffer> frakL 𝔏
abbrev <buffer> frakM 𝔐
abbrev <buffer> frakN 𝔑
abbrev <buffer> frakO 𝔒
abbrev <buffer> frakP 𝔓
abbrev <buffer> frakQ 𝔔
abbrev <buffer> frakR ℜ
abbrev <buffer> frakS 𝔖
abbrev <buffer> frakT 𝔗
abbrev <buffer> frakU 𝔘
abbrev <buffer> frakV 𝔙
abbrev <buffer> frakW 𝔚
abbrev <buffer> frakX 𝔛
abbrev <buffer> frakY 𝔜
abbrev <buffer> frakZ ℨ
abbrev <buffer> fraka 𝔞
abbrev <buffer> frakb 𝔟
abbrev <buffer> frakc 𝔠
abbrev <buffer> frakd 𝔡
abbrev <buffer> frake 𝔢
abbrev <buffer> frakf 𝔣
abbrev <buffer> frakg 𝔤
abbrev <buffer> frakh 𝔥
abbrev <buffer> fraki 𝔦
abbrev <buffer> frakj 𝔧
abbrev <buffer> frakk 𝔨
abbrev <buffer> frakl 𝔩
abbrev <buffer> frakm 𝔪
abbrev <buffer> frakn 𝔫
abbrev <buffer> frako 𝔬
abbrev <buffer> frakp 𝔭
abbrev <buffer> frakq 𝔮
abbrev <buffer> frakr 𝔯
abbrev <buffer> fraks 𝔰
abbrev <buffer> frakt 𝔱
abbrev <buffer> fraku 𝔲
abbrev <buffer> frakv 𝔳
abbrev <buffer> frakw 𝔴
abbrev <buffer> frakx 𝔵
abbrev <buffer> fraky 𝔶
abbrev <buffer> frakz 𝔷
abbrev <buffer> bfrakA 𝕬
abbrev <buffer> bfrakB 𝕭
abbrev <buffer> bfrakC 𝕮
abbrev <buffer> bfrakD 𝕯
abbrev <buffer> bfrakE 𝕰
abbrev <buffer> bfrakF 𝕱
abbrev <buffer> bfrakG 𝕲
abbrev <buffer> bfrakH 𝕳
abbrev <buffer> bfrakI 𝕴
abbrev <buffer> bfrakJ 𝕵
abbrev <buffer> bfrakK 𝕶
abbrev <buffer> bfrakL 𝕷
abbrev <buffer> bfrakM 𝕸
abbrev <buffer> bfrakN 𝕹
abbrev <buffer> bfrakO 𝕺
abbrev <buffer> bfrakP 𝕻
abbrev <buffer> bfrakQ 𝕼
abbrev <buffer> bfrakR 𝕽
abbrev <buffer> bfrakS 𝕾
abbrev <buffer> bfrakT 𝕿
abbrev <buffer> bfrakU 𝖀
abbrev <buffer> bfrakV 𝖁
abbrev <buffer> bfrakW 𝖂
abbrev <buffer> bfrakX 𝖃
abbrev <buffer> bfrakY 𝖄
abbrev <buffer> bfrakZ 𝖅
abbrev <buffer> bfraka 𝖆
abbrev <buffer> bfrakb 𝖇
abbrev <buffer> bfrakc 𝖈
abbrev <buffer> bfrakd 𝖉
abbrev <buffer> bfrake 𝖊
abbrev <buffer> bfrakf 𝖋
abbrev <buffer> bfrakg 𝖌
abbrev <buffer> bfrakh 𝖍
abbrev <buffer> bfraki 𝖎
abbrev <buffer> bfrakj 𝖏
abbrev <buffer> bfrakk 𝖐
abbrev <buffer> bfrakl 𝖑
abbrev <buffer> bfrakm 𝖒
abbrev <buffer> bfrakn 𝖓
abbrev <buffer> bfrako 𝖔
abbrev <buffer> bfrakp 𝖕
abbrev <buffer> bfrakq 𝖖
abbrev <buffer> bfrakr 𝖗
abbrev <buffer> bfraks 𝖘
abbrev <buffer> bfrakt 𝖙
abbrev <buffer> bfraku 𝖚
abbrev <buffer> bfrakv 𝖛
abbrev <buffer> bfrakw 𝖜
abbrev <buffer> bfrakx 𝖝
abbrev <buffer> bfraky 𝖞
abbrev <buffer> bfrakz 𝖟
abbrev <buffer> ^0 ⁰
abbrev <buffer> ^1 ¹
abbrev <buffer> ^2 ²
abbrev <buffer> ^3 ³
abbrev <buffer> ^4 ⁴
abbrev <buffer> ^5 ⁵
abbrev <buffer> ^6 ⁶
abbrev <buffer> ^7 ⁷
abbrev <buffer> ^8 ⁸
abbrev <buffer> ^9 ⁹
abbrev <buffer> ^+ ⁺
abbrev <buffer> ^- ⁻
abbrev <buffer> ^= ⁼
abbrev <buffer> ^( ⁽
abbrev <buffer> ^) ⁾
abbrev <buffer> ^A ᴬ
abbrev <buffer> ^B ᴮ
abbrev <buffer> ^D ᴰ
abbrev <buffer> ^E ᴱ
abbrev <buffer> ^G ᴳ
abbrev <buffer> ^H ᴴ
abbrev <buffer> ^I ᴵ
abbrev <buffer> ^J ᴶ
abbrev <buffer> ^K ᴷ
abbrev <buffer> ^L ᴸ
abbrev <buffer> ^M ᴹ
abbrev <buffer> ^N ᴺ
abbrev <buffer> ^O ᴼ
abbrev <buffer> ^P ᴾ
abbrev <buffer> ^R ᴿ
abbrev <buffer> ^T ᵀ
abbrev <buffer> ^U ᵁ
abbrev <buffer> ^V ⱽ
abbrev <buffer> ^W ᵂ
abbrev <buffer> ^a ᵃ
abbrev <buffer> ^b ᵇ
abbrev <buffer> ^c ᶜ
abbrev <buffer> ^d ᵈ
abbrev <buffer> ^e ᵉ
abbrev <buffer> ^f ᶠ
abbrev <buffer> ^g ᵍ
abbrev <buffer> ^h ʰ
abbrev <buffer> ^i ⁱ
abbrev <buffer> ^j ʲ
abbrev <buffer> ^k ᵏ
abbrev <buffer> ^l ˡ
abbrev <buffer> ^m ᵐ
abbrev <buffer> ^n ⁿ
abbrev <buffer> ^o ᵒ
abbrev <buffer> ^p ᵖ
abbrev <buffer> ^r ʳ
abbrev <buffer> ^s ˢ
abbrev <buffer> ^t ᵗ
abbrev <buffer> ^u ᵘ
abbrev <buffer> ^v ᵛ
abbrev <buffer> ^w ʷ
abbrev <buffer> ^x ˣ
abbrev <buffer> ^y ʸ
abbrev <buffer> ^z ᶻ
abbrev <buffer> _1 ₀
abbrev <buffer> _2 ₁
abbrev <buffer> _3 ₂
abbrev <buffer> _4 ₃
abbrev <buffer> _5 ₄
abbrev <buffer> _6 ₅
abbrev <buffer> _7 ₆
abbrev <buffer> _8 ₇
abbrev <buffer> _9 ₈
abbrev <buffer> _10 ₉
abbrev <buffer> _+ ₊
abbrev <buffer> _- ₋
abbrev <buffer> _= ₌
abbrev <buffer> _( ₍
abbrev <buffer> _) ₎
abbrev <buffer> _a ₐ
abbrev <buffer> _e ₑ
abbrev <buffer> _h ₕ
abbrev <buffer> _i ᵢ
abbrev <buffer> _j ⱼ
abbrev <buffer> _k ₖ
abbrev <buffer> _l ₗ
abbrev <buffer> _m ₘ
abbrev <buffer> _n ₙ
abbrev <buffer> _o ₒ
abbrev <buffer> _p ₚ
abbrev <buffer> _r ᵣ
abbrev <buffer> _s ₛ
abbrev <buffer> _t ₜ
abbrev <buffer> _u ᵤ
abbrev <buffer> _v ᵥ
abbrev <buffer> _x ₓ
abbrev <buffer> blank ⠀
abbrev <buffer> Alpha Α
abbrev <buffer> Beta Β
abbrev <buffer> Gamma Γ
abbrev <buffer> Delta Δ
abbrev <buffer> Epsilon Ε
abbrev <buffer> Zeta Ζ
abbrev <buffer> Eta Η
abbrev <buffer> Theta Θ
abbrev <buffer> Iota Ι
abbrev <buffer> Kappa Κ
abbrev <buffer> Lambda Λ
abbrev <buffer> Mu Μ
abbrev <buffer> Nu Ν
abbrev <buffer> Xi Ξ
abbrev <buffer> Omicron Ο
abbrev <buffer> Pi Π
abbrev <buffer> Rho Ρ
abbrev <buffer> Sigma Σ
abbrev <buffer> Tau Τ
abbrev <buffer> Upsilon Υ
abbrev <buffer> Phi Φ
abbrev <buffer> Chi Χ
abbrev <buffer> Psi Ψ
abbrev <buffer> Omega Ω
abbrev <buffer> alpha α
abbrev <buffer> beta β
abbrev <buffer> curbeta ϐ
abbrev <buffer> gamma γ
abbrev <buffer> delta δ
abbrev <buffer> epsilon ε
abbrev <buffer> lunepsilon ϵ
abbrev <buffer> zeta ζ
abbrev <buffer> eta η
abbrev <buffer> theta ϑ
abbrev <buffer> vtheta θ
abbrev <buffer> iota ι
abbrev <buffer> kappa κ
abbrev <buffer> curkappa ϰ
abbrev <buffer> lambda λ
abbrev <buffer> mu μ
abbrev <buffer> nu ν
abbrev <buffer> xi ξ
abbrev <buffer> omicron ο
abbrev <buffer> pi π
abbrev <buffer> curpi ϖ
abbrev <buffer> rho ρ
abbrev <buffer> currho ϱ
abbrev <buffer> sigma σ
abbrev <buffer> finsigma ς
abbrev <buffer> tau τ
abbrev <buffer> upsilon υ
abbrev <buffer> phi φ
abbrev <buffer> clophi ϕ
abbrev <buffer> chi χ
abbrev <buffer> psi ψ
abbrev <buffer> omega ω
abbrev <buffer> eur €
abbrev <buffer> gbp £
abbrev <buffer> usd $
abbrev <buffer> yen ¥
abbrev <buffer> brl R$
abbrev <buffer> spc ␣
abbrev <buffer> nbsp  
abbrev <buffer> return ⏎
abbrev <buffer> lqua ⌜
abbrev <buffer> rqua ⌝
abbrev <buffer> langle ⟨
abbrev <buffer> rangle ⟩
abbrev <buffer> lceil ⌈
abbrev <buffer> rceil ⌉
abbrev <buffer> lfloor ⌊
abbrev <buffer> rfloor ⌋
abbrev <buffer> lbag ⟅
abbrev <buffer> rbag ⟆
abbrev <buffer> lsem ⟦
abbrev <buffer> rsem ⟧
abbrev <buffer> lSet ⦃
abbrev <buffer> rSet ⦄
abbrev <buffer> lPar ⦅
abbrev <buffer> rPar ⦆
abbrev <buffer> lban ⦇
abbrev <buffer> rban ⦈
abbrev <buffer> lAngle ⦉
abbrev <buffer> rAngle ⦊
abbrev <buffer> lnorm ‖
abbrev <buffer> rnorm ‖
abbrev <buffer> halmos ∎
abbrev <buffer> qed ∎
abbrev <buffer> leq ≤
abbrev <buffer> geq ≥
abbrev <buffer> neq ≠
abbrev <buffer> nlt ≮
abbrev <buffer> ngt ≯
abbrev <buffer> nleq ≰
abbrev <buffer> ngeq ≱
abbrev <buffer> div ∣
abbrev <buffer> ndiv ∤
abbrev <buffer> forall ∀
abbrev <buffer> exists ∃
abbrev <buffer> nexists ∄
abbrev <buffer> implies ⇒
abbrev <buffer> implied ⇐
abbrev <buffer> iff ⇔
abbrev <buffer> timplies ⟹
abbrev <buffer> timplied ⟸
abbrev <buffer> tiff ⟺
abbrev <buffer> vimplies ⇓
abbrev <buffer> vimplied ⇑
abbrev <buffer> viff ⇕
abbrev <buffer> rlarr ⇄
abbrev <buffer> lrarr ⇆
abbrev <buffer> tofrom ⇄
abbrev <buffer> fromto ⇆
abbrev <buffer> udarr ⇅
abbrev <buffer> uuarr ⇈
abbrev <buffer> ddarr ⇊
abbrev <buffer> llarr ⇇
abbrev <buffer> rrarr ⇉
abbrev <buffer> uarr ↑
abbrev <buffer> darr ↓
abbrev <buffer> larr ←
abbrev <buffer> rarr →
abbrev <buffer> nimplied ⇍
abbrev <buffer> nimplies ⇏
abbrev <buffer> niff ⇎
abbrev <buffer> inteq ≡
abbrev <buffer> intneq ≢
abbrev <buffer> defeq ≝
abbrev <buffer> doteq ≐
abbrev <buffer> askeq ≟
abbrev <buffer> asteq ⩮
abbrev <buffer> stareq ≛
abbrev <buffer> defiff ⇐≝⇒
abbrev <buffer> intiff ⇚⇛
abbrev <buffer> intimplies ⇛
abbrev <buffer> vintimplied ⤊
abbrev <buffer> vintimplies ⤋
abbrev <buffer> intimplied ⇚
abbrev <buffer> ledfrom ↜
abbrev <buffer> leadsto ↝
abbrev <buffer> rleads ↝
abbrev <buffer> lleads ↜
abbrev <buffer> eqto ⥱
abbrev <buffer> isoto ⥲
abbrev <buffer> Funto ⥤
abbrev <buffer> therefore ∴
abbrev <buffer> because ∵
abbrev <buffer> vdots ⋮
abbrev <buffer> hdots ⋯
abbrev <buffer> cdots ⋯
abbrev <buffer> dotsb ⋯
abbrev <buffer> ldots …
abbrev <buffer> dotsc …
abbrev <buffer> pm ±
abbrev <buffer> mp ∓
abbrev <buffer> infty ∞
abbrev <buffer> pinfty +∞
abbrev <buffer> minfty -∞
abbrev <buffer> pminfty ±∞
abbrev <buffer> mpinfty ∓∞
abbrev <buffer> surd √
abbrev <buffer> integ ∫
abbrev <buffer> iinteg ∬
abbrev <buffer> iiinteg ∭
abbrev <buffer> ointeg ∮
abbrev <buffer> nabla ∇
abbrev <buffer> partial ∂
abbrev <buffer> ast ∗
abbrev <buffer> star ⋆
abbrev <buffer> bullet ∙
abbrev <buffer> cdot ·
abbrev <buffer> ntimes ·
abbrev <buffer> cross ×
abbrev <buffer> times ×
abbrev <buffer> circ ∘
abbrev <buffer> oplus ⊕
abbrev <buffer> ominus ⊖
abbrev <buffer> otimes ⊗
abbrev <buffer> tensor ⊗
abbrev <buffer> ocross ⊗
abbrev <buffer> odiv ⊘
abbrev <buffer> odot ⊙
abbrev <buffer> dotminus ∸
abbrev <buffer> dotplus ⨢
abbrev <buffer> monus ∸
abbrev <buffer> dottimes ⨰
abbrev <buffer> uplus ⊎
abbrev <buffer> Uplus ⨄
abbrev <buffer> dhole –
abbrev <buffer> hole _
abbrev <buffer> emptyset Ø
abbrev <buffer> empty Ø
abbrev <buffer> bools 𝔹
abbrev <buffer> nats ℕ
abbrev <buffer> ints ℤ
abbrev <buffer> rats ℚ
abbrev <buffer> reals ℝ
abbrev <buffer> complex ℂ
abbrev <buffer> in ∈
abbrev <buffer> notin ∉
abbrev <buffer> nin ∉
abbrev <buffer> ni ∋
abbrev <buffer> notni ∌
abbrev <buffer> nni ∌
abbrev <buffer> Inter ⋂
abbrev <buffer> Union ⋃
abbrev <buffer> inter ∩
abbrev <buffer> union ∪
abbrev <buffer> disjunion ⊎
abbrev <buffer> Disjunion ⨄
abbrev <buffer> dunion ⊎
abbrev <buffer> Dunion ⨄
abbrev <buffer> symdiff ∆
abbrev <buffer> sdiff ∆
abbrev <buffer> setminus ∖
abbrev <buffer> minus ∖
abbrev <buffer> subset ⊆
abbrev <buffer> supset ⊇
abbrev <buffer> psubset ⊊
abbrev <buffer> psupset ⊋
abbrev <buffer> hsubset ⊂
abbrev <buffer> hsupset ⊃
abbrev <buffer> nsubset ⊈
abbrev <buffer> nsupset ⊉
abbrev <buffer> subsetneq ⊊
abbrev <buffer> supsetneq ⊋
abbrev <buffer> sqleq ⊑
abbrev <buffer> sqgeq ⊒
abbrev <buffer> sqlt ⊏
abbrev <buffer> sqgt ⊐
abbrev <buffer> sqlneq ⋤
abbrev <buffer> sqgneq ⋥
abbrev <buffer> sqnleq ⋢
abbrev <buffer> sqngeq ⋣
abbrev <buffer> semleq ⊑
abbrev <buffer> semgeq ⊒
abbrev <buffer> semlneq ⋤
abbrev <buffer> semgneq ⋥
abbrev <buffer> nsemleq ⋢
abbrev <buffer> nsemgeq ⋣
abbrev <buffer> domleq ⊑
abbrev <buffer> domgeq ⊒
abbrev <buffer> domlneq ⋤
abbrev <buffer> domgneq ⋥
abbrev <buffer> pset ℘
abbrev <buffer> aleph ℵ
abbrev <buffer> beth ℶ
abbrev <buffer> gimel ℷ
abbrev <buffer> comp ∘
abbrev <buffer> to →
abbrev <buffer> from ←
abbrev <buffer> nto ↛
abbrev <buffer> nfrom ↚
abbrev <buffer> parto ⇀
abbrev <buffer> mapsto ↦
abbrev <buffer> mapsfrom ↤
abbrev <buffer> tmapsto ⟼
abbrev <buffer> tmapsfrom ⟻
abbrev <buffer> mapsup ↥
abbrev <buffer> mapsdown ↧
abbrev <buffer> parfrom ↼
abbrev <buffer> rest ↾
abbrev <buffer> surto ↠
abbrev <buffer> surfrom ↞
abbrev <buffer> injto ↣
abbrev <buffer> injfrom ↢
abbrev <buffer> embto ↪
abbrev <buffer> embfrom ↩
abbrev <buffer> bijto ⤖
abbrev <buffer> relto ⇾
abbrev <buffer> relfrom ⇽
abbrev <buffer> dual ∂
abbrev <buffer> ndetfrom ⇜
abbrev <buffer> ndetto ⇝
abbrev <buffer> dfrom ⇠
abbrev <buffer> dto ⇢
abbrev <buffer> equiv ≅
abbrev <buffer> nequiv ≇
abbrev <buffer> iso ≅
abbrev <buffer> niso ≇
abbrev <buffer> rcomp ⋄
abbrev <buffer> cong ≡
abbrev <buffer> ncong ≢
abbrev <buffer> normal ⊴
abbrev <buffer> pnormal ⊲
abbrev <buffer> sim ~
abbrev <buffer> nsim ≁
abbrev <buffer> approx ≈
abbrev <buffer> napprox ≉
abbrev <buffer> Prod ∏
abbrev <buffer> Coprod ∐
abbrev <buffer> coprod ⨿
abbrev <buffer> Sum ∑
abbrev <buffer> op ᵒᵖ
abbrev <buffer> concat ⧺
abbrev <buffer> inv ⁻¹
abbrev <buffer> lnot ¬
abbrev <buffer> lforall ∀
abbrev <buffer> lexists ∃
abbrev <buffer> limplies →
abbrev <buffer> limplied ←
abbrev <buffer> liff ↔
abbrev <buffer> land ∧
abbrev <buffer> lor ∨
abbrev <buffer> Land ⋀
abbrev <buffer> Lor ⋁
abbrev <buffer> sequent ⊢
abbrev <buffer> proves ⊢
abbrev <buffer> nproves ⊬
abbrev <buffer> models ⊨
abbrev <buffer> nmodels ⊭
abbrev <buffer> forces ⊩
abbrev <buffer> nforces ⊮
abbrev <buffer> linnot ⊥
abbrev <buffer> linto ⊸
abbrev <buffer> linwith &
abbrev <buffer> linpar ⅋
abbrev <buffer> himplies ⥰
abbrev <buffer> horse ⥰
abbrev <buffer> top ⊤
abbrev <buffer> bottom ⊥
abbrev <buffer> Meet ⋀
abbrev <buffer> Join ⋁
abbrev <buffer> meet ∧
abbrev <buffer> join ∨
abbrev <buffer> incompar ≸
abbrev <buffer> incompat ‖
abbrev <buffer> wbelow ≪
abbrev <buffer> wabove ≫
abbrev <buffer> domlt ⊏
abbrev <buffer> domgt ⊐
abbrev <buffer> domleq ⊑
abbrev <buffer> domgeq ⊒
abbrev <buffer> glb ⊓
abbrev <buffer> lub ⊔
abbrev <buffer> Glb ⨅
abbrev <buffer> Lub ⨆
abbrev <buffer> spades ♠
abbrev <buffer> hearts ♡
abbrev <buffer> diamonds ♢
abbrev <buffer> clubs ♣
abbrev <buffer> magic ⛤
abbrev <buffer> rturnstile ⊢
abbrev <buffer> lturnstile ⊣
abbrev <buffer> sqleftarrow ⇜
abbrev <buffer> sqrightarrow ⇝
abbrev <buffer> sqbotharrow ↭
abbrev <buffer> nwarrow ↖
abbrev <buffer> nearrow ↗
abbrev <buffer> swarrow ↙
abbrev <buffer> searrow ↘
abbrev <buffer> duparrow ⇡
abbrev <buffer> drightarrow ⇢
abbrev <buffer> ddownarrow ⇣
abbrev <buffer> dleftarrow ⇠
abbrev <buffer> up ↑
abbrev <buffer> down ↓
abbrev <buffer> left ←
abbrev <buffer> right →
abbrev <buffer> Ell ℒ
abbrev <buffer> ell ℓ
abbrev <buffer> bang !
abbrev <buffer> gnab ¡
abbrev <buffer> bbang ‼
abbrev <buffer> ibang ‽
abbrev <buffer> ignab ⸘
abbrev <buffer> abang ⁈
abbrev <buffer> bask ⁉
abbrev <buffer> frown ⌢
abbrev <buffer> smile ⌣
abbrev <buffer> utri △
abbrev <buffer> dtri ▽
abbrev <buffer> ltri ◁
abbrev <buffer> rtri ▷
abbrev <buffer> utris ▵
abbrev <buffer> dtris ▿
abbrev <buffer> ltris ◃
abbrev <buffer> rtris ▹
abbrev <buffer> ubtri ▲
abbrev <buffer> dbtri ▼
abbrev <buffer> lbtri ◄
abbrev <buffer> rbtri ►
abbrev <buffer> ubtris ▴
abbrev <buffer> dbtris ▾
abbrev <buffer> lbtris ◂
abbrev <buffer> rbtris ▸
abbrev <buffer> CAT 𝐂𝐚𝐭
abbrev <buffer> SET 𝐒𝐞𝐭
abbrev <buffer> PSET 𝐏𝐒𝐞𝐭
abbrev <buffer> PTDSET 𝐏𝐭𝐝𝐒𝐞𝐭
abbrev <buffer> FINSET 𝐅𝐢𝐧𝐒𝐞𝐭
abbrev <buffer> FINORD 𝐅𝐢𝐧𝐎𝐫𝐝
abbrev <buffer> ORD 𝐎𝐫𝐝
abbrev <buffer> PROSET 𝐏𝐫𝐨𝐬𝐞𝐭
abbrev <buffer> POSET 𝐏𝐨𝐬𝐞𝐭
abbrev <buffer> SGROUP 𝐒𝐞𝐦𝐢𝐠𝐫𝐨𝐮𝐩
abbrev <buffer> SGRP 𝐒𝐞𝐦𝐢𝐠𝐫𝐩
abbrev <buffer> MON 𝐌𝐨𝐧
abbrev <buffer> MONOID 𝐌𝐨𝐧𝐨𝐢𝐝
abbrev <buffer> GROUP 𝐆𝐫𝐨𝐮𝐩
abbrev <buffer> GRP 𝐆𝐫𝐩
abbrev <buffer> ABEL 𝐀𝐛𝐞𝐥
abbrev <buffer> RING 𝐑𝐢𝐧𝐠
abbrev <buffer> RNG 𝐑𝐧𝐠
abbrev <buffer> RIG 𝐑𝐢𝐠
abbrev <buffer> MOD 𝐌𝐨𝐝
abbrev <buffer> MAT 𝐌𝐚𝐭𝐫𝐢𝐱
abbrev <buffer> LAT 𝐋𝐚𝐭𝐭𝐢𝐜𝐞
abbrev <buffer> HALG 𝐇𝐞𝐲𝐭𝐢𝐧𝐠
abbrev <buffer> BALG 𝐁𝐨𝐨𝐥𝐞𝐚𝐧
abbrev <buffer> HA 𝐇𝐀
abbrev <buffer> BA 𝐁𝐀
abbrev <buffer> MODEL 𝐌𝐨𝐝𝐞𝐥
abbrev <buffer> psubs ⊊
abbrev <buffer> psups ⊋
abbrev <buffer> hsubs ⊂
abbrev <buffer> hsups ⊃
abbrev <buffer> nsubs ⊈
abbrev <buffer> nsups ⊉
abbrev <buffer> subsne ⊊
abbrev <buffer> supsne ⊋
abbrev <buffer> fa ∀
abbrev <buffer> ex ∃
abbrev <buffer> nex ∄
abbrev <buffer> imps ⇒
abbrev <buffer> impd ⇐
abbrev <buffer> iff ⇔
abbrev <buffer> timps ⟹
abbrev <buffer> timpd ⟸
abbrev <buffer> tiff ⟺
abbrev <buffer> vimps ⇓
abbrev <buffer> vimpd ⇑
abbrev <buffer> nimpd ⇍
abbrev <buffer> nimps ⇏
abbrev <buffer> rmaps ↦
abbrev <buffer> lmaps ↤
abbrev <buffer> Rmaps ⟼
abbrev <buffer> Lmaps ⟻
abbrev <buffer> there ∴
abbrev <buffer> cause ∵
abbrev <buffer> dplus ⨢
abbrev <buffer> dtimes ⨰
