let maplocalleader=" "

set spelllang=pt_br

nnoremap <localleader><localleader> :set spell!<cr>
nnoremap <localleader>n ]s
nnoremap <localleader>N [s
nnoremap <localleader>b 1z=
nnoremap <localleader>gf I<esc>f(lgf

"modified unicodef (github.com/tsouanas/unicodef)
abbrev bomb 💣
abbrev boom 💥
abbrev bulb 💡
abbrev hrmf ⍨
abbrev pirate ☠
abbrev poo 💩
abbrev smooch ⍣
abbrev zzz 💤
abbrev tada 🎉
abbrev scrA 𝒜
abbrev scrB ℬ
abbrev scrC 𝒞
abbrev scrD 𝒟
abbrev scrE ℰ
abbrev scrF ℱ
abbrev scrG 𝒢
abbrev scrH ℋ
abbrev scrI ℐ
abbrev scrJ 𝒥
abbrev scrK 𝒦
abbrev scrL ℒ
abbrev scrM ℳ
abbrev scrN 𝒩
abbrev scrO 𝒪
abbrev scrP 𝒫
abbrev scrQ 𝒬
abbrev scrR ℛ
abbrev scrS 𝒮
abbrev scrT 𝒯
abbrev scrU 𝒰
abbrev scrV 𝒱
abbrev scrW 𝒲
abbrev scrX 𝒳
abbrev scrY 𝒴
abbrev scrZ 𝒵
abbrev scra 𝒶
abbrev scrb 𝒷
abbrev scrc 𝒸
abbrev scrd 𝒹
abbrev scre ℯ
abbrev scrf 𝒻
abbrev scrg ℊ
abbrev scrh 𝒽
abbrev scri 𝒾
abbrev scrj 𝒿
abbrev scrk 𝓀
abbrev scrl 𝓁
abbrev scrm 𝓂
abbrev scrn 𝓃
abbrev scro ℴ
abbrev scrp 𝓅
abbrev scrq 𝓆
abbrev scrr 𝓇
abbrev scrs 𝓈
abbrev scrt 𝓉
abbrev scru 𝓊
abbrev scrv 𝓋
abbrev scrw 𝓌
abbrev scrx 𝓍
abbrev scry 𝓎
abbrev scrz 𝓏
abbrev calA 𝓐
abbrev calB 𝓑
abbrev calC 𝓒
abbrev calD 𝓓
abbrev calE 𝓔
abbrev calF 𝓕
abbrev calG 𝓖
abbrev calH 𝓗
abbrev calI 𝓘
abbrev calJ 𝓙
abbrev calK 𝓚
abbrev calL 𝓛
abbrev calM 𝓜
abbrev calN 𝓝
abbrev calO 𝓞
abbrev calP 𝓟
abbrev calQ 𝓠
abbrev calR 𝓡
abbrev calS 𝓢
abbrev calT 𝓣
abbrev calU 𝓤
abbrev calV 𝓥
abbrev calW 𝓦
abbrev calX 𝓧
abbrev calY 𝓨
abbrev calZ 𝓩
abbrev cala 𝓪
abbrev calb 𝓫
abbrev calc 𝓬
abbrev cald 𝓭
abbrev cale 𝓮
abbrev calf 𝓯
abbrev calg 𝓰
abbrev calh 𝓱
abbrev cali 𝓲
abbrev calj 𝓳
abbrev calk 𝓴
abbrev call 𝓵
abbrev calm 𝓶
abbrev caln 𝓷
abbrev calo 𝓸
abbrev calp 𝓹
abbrev calq 𝓺
abbrev calr 𝓻
abbrev cals 𝓼
abbrev calt 𝓽
abbrev calu 𝓾
abbrev calv 𝓿
abbrev calw 𝔀
abbrev calx 𝔁
abbrev caly 𝔂
abbrev calz 𝔃
abbrev ttA 𝙰
abbrev ttB 𝙱
abbrev ttC 𝙲
abbrev ttD 𝙳
abbrev ttE 𝙴
abbrev ttF 𝙵
abbrev ttG 𝙶
abbrev ttH 𝙷
abbrev ttI 𝙸
abbrev ttJ 𝙹
abbrev ttK 𝙺
abbrev ttL 𝙻
abbrev ttM 𝙼
abbrev ttN 𝙽
abbrev ttO 𝙾
abbrev ttP 𝙿
abbrev ttQ 𝚀
abbrev ttR 𝚁
abbrev ttS 𝚂
abbrev ttT 𝚃
abbrev ttU 𝚄
abbrev ttV 𝚅
abbrev ttW 𝚆
abbrev ttX 𝚇
abbrev ttY 𝚈
abbrev ttZ 𝚉
abbrev tta 𝚊
abbrev ttb 𝚋
abbrev ttc 𝚌
abbrev ttd 𝚍
abbrev tte 𝚎
abbrev ttf 𝚏
abbrev ttg 𝚐
abbrev tth 𝚑
abbrev tti 𝚒
abbrev ttj 𝚓
abbrev ttk 𝚔
abbrev ttl 𝚕
abbrev ttm 𝚖
abbrev ttn 𝚗
abbrev tto 𝚘
abbrev ttp 𝚙
abbrev ttq 𝚚
abbrev ttr 𝚛
abbrev tts 𝚜
abbrev ttt 𝚝
abbrev ttu 𝚞
abbrev ttv 𝚟
abbrev ttw 𝚠
abbrev ttx 𝚡
abbrev tty 𝚢
abbrev ttz 𝚣
abbrev itA 𝐴
abbrev itB 𝐵
abbrev itC 𝐶
abbrev itD 𝐷
abbrev itE 𝐸
abbrev itF 𝐹
abbrev itG 𝐺
abbrev itH 𝐻
abbrev itI 𝐼
abbrev itJ 𝐽
abbrev itK 𝐾
abbrev itL 𝐿
abbrev itM 𝑀
abbrev itN 𝑁
abbrev itO 𝑂
abbrev itP 𝑃
abbrev itQ 𝑄
abbrev itR 𝑅
abbrev itS 𝑆
abbrev itT 𝑇
abbrev itU 𝑈
abbrev itV 𝑉
abbrev itW 𝑊
abbrev itX 𝑋
abbrev itY 𝑌
abbrev itZ 𝑍
abbrev ita 𝑎
abbrev itb 𝑏
abbrev itc 𝑐
abbrev itd 𝑑
abbrev ite 𝑒
abbrev itf 𝑓
abbrev itg 𝑔
abbrev ith ℎ
abbrev iti 𝑖
abbrev itj 𝑗
abbrev itk 𝑘
abbrev itl 𝑙
abbrev itm 𝑚
abbrev itn 𝑛
abbrev ito 𝑜
abbrev itp 𝑝
abbrev itq 𝑞
abbrev itr 𝑟
abbrev its 𝑠
abbrev itt 𝑡
abbrev itu 𝑢
abbrev itv 𝑣
abbrev itw 𝑤
abbrev itx 𝑥
abbrev ity 𝑦
abbrev itz 𝑧
abbrev isA 𝘈
abbrev isB 𝘉
abbrev isC 𝘊
abbrev isD 𝘋
abbrev isE 𝘌
abbrev isF 𝘍
abbrev isG 𝘎
abbrev isH 𝘏
abbrev isI 𝘐
abbrev isJ 𝘑
abbrev isK 𝘒
abbrev isL 𝘓
abbrev isM 𝘔
abbrev isN 𝘕
abbrev isO 𝘖
abbrev isP 𝘗
abbrev isQ 𝘘
abbrev isR 𝘙
abbrev isS 𝘚
abbrev isT 𝘛
abbrev isU 𝘜
abbrev isV 𝘝
abbrev isW 𝘞
abbrev isX 𝘟
abbrev isY 𝘠
abbrev isZ 𝘡
abbrev isa 𝘢
abbrev isb 𝘣
abbrev isc 𝘤
abbrev isd 𝘥
abbrev ise 𝘦
abbrev isf 𝘧
abbrev isg 𝘨
abbrev ish 𝘩
abbrev isi 𝘪
abbrev isj 𝘫
abbrev isk 𝘬
abbrev isl 𝘭
abbrev ism 𝘮
abbrev isn 𝘯
abbrev iso 𝘰
abbrev isp 𝘱
abbrev isq 𝘲
abbrev isr 𝘳
abbrev iss 𝘴
abbrev ist 𝘵
abbrev isu 𝘶
abbrev isv 𝘷
abbrev isw 𝘸
abbrev isx 𝘹
abbrev isy 𝘺
abbrev isz 𝘻
abbrev bfA 𝐀
abbrev bfB 𝐁
abbrev bfC 𝐂
abbrev bfD 𝐃
abbrev bfE 𝐄
abbrev bfF 𝐅
abbrev bfG 𝐆
abbrev bfH 𝐇
abbrev bfI 𝐈
abbrev bfJ 𝐉
abbrev bfK 𝐊
abbrev bfL 𝐋
abbrev bfM 𝐌
abbrev bfN 𝐍
abbrev bfO 𝐎
abbrev bfP 𝐏
abbrev bfQ 𝐐
abbrev bfR 𝐑
abbrev bfS 𝐒
abbrev bfT 𝐓
abbrev bfU 𝐔
abbrev bfV 𝐕
abbrev bfW 𝐖
abbrev bfX 𝐗
abbrev bfY 𝐘
abbrev bfZ 𝐙
abbrev bfa 𝐚
abbrev bfb 𝐛
abbrev bfc 𝐜
abbrev bfd 𝐝
abbrev bfe 𝐞
abbrev bff 𝐟
abbrev bfg 𝐠
abbrev bfh 𝐡
abbrev bfi 𝐢
abbrev bfj 𝐣
abbrev bfk 𝐤
abbrev bfl 𝐥
abbrev bfm 𝐦
abbrev bfn 𝐧
abbrev bfo 𝐨
abbrev bfp 𝐩
abbrev bfq 𝐪
abbrev bfr 𝐫
abbrev bfs 𝐬
abbrev bft 𝐭
abbrev bfu 𝐮
abbrev bfv 𝐯
abbrev bfw 𝐰
abbrev bfx 𝐱
abbrev bfy 𝐲
abbrev bfz 𝐳
abbrev bf1 𝟎
abbrev bf2 𝟏
abbrev bf3 𝟐
abbrev bf4 𝟑
abbrev bf5 𝟒
abbrev bf6 𝟓
abbrev bf7 𝟔
abbrev bf8 𝟕
abbrev bf9 𝟖
abbrev bf10 𝟗
abbrev bfiA 𝑨
abbrev bfiB 𝑩
abbrev bfiC 𝑪
abbrev bfiD 𝑫
abbrev bfiE 𝑬
abbrev bfiF 𝑭
abbrev bfiG 𝑮
abbrev bfiH 𝑯
abbrev bfiI 𝑰
abbrev bfiJ 𝑱
abbrev bfiK 𝑲
abbrev bfiL 𝑳
abbrev bfiM 𝑴
abbrev bfiN 𝑵
abbrev bfiO 𝑶
abbrev bfiP 𝑷
abbrev bfiQ 𝑸
abbrev bfiR 𝑹
abbrev bfiS 𝑺
abbrev bfiT 𝑻
abbrev bfiU 𝑼
abbrev bfiV 𝑽
abbrev bfiW 𝑾
abbrev bfiX 𝑿
abbrev bfiY 𝒀
abbrev bfiZ 𝒁
abbrev bfia 𝒂
abbrev bfib 𝒃
abbrev bfic 𝒄
abbrev bfid 𝒅
abbrev bfie 𝒆
abbrev bfif 𝒇
abbrev bfig 𝒈
abbrev bfih 𝒉
abbrev bfii 𝒊
abbrev bfij 𝒋
abbrev bfik 𝒌
abbrev bfil 𝒍
abbrev bfim 𝒎
abbrev bfin 𝒏
abbrev bfio 𝒐
abbrev bfip 𝒑
abbrev bfiq 𝒒
abbrev bfir 𝒓
abbrev bfis 𝒔
abbrev bfit 𝒕
abbrev bfiu 𝒖
abbrev bfiv 𝒗
abbrev bfiw 𝒘
abbrev bfix 𝒙
abbrev bfiy 𝒚
abbrev bfiz 𝒛
abbrev bsA 𝗔
abbrev bsB 𝗕
abbrev bsC 𝗖
abbrev bsD 𝗗
abbrev bsE 𝗘
abbrev bsF 𝗙
abbrev bsG 𝗚
abbrev bsH 𝗛
abbrev bsI 𝗜
abbrev bsJ 𝗝
abbrev bsK 𝗞
abbrev bsL 𝗟
abbrev bsM 𝗠
abbrev bsN 𝗡
abbrev bsO 𝗢
abbrev bsP 𝗣
abbrev bsQ 𝗤
abbrev bsR 𝗥
abbrev bsS 𝗦
abbrev bsT 𝗧
abbrev bsU 𝗨
abbrev bsV 𝗩
abbrev bsW 𝗪
abbrev bsX 𝗫
abbrev bsY 𝗬
abbrev bsZ 𝗭
abbrev bsa 𝗮
abbrev bsb 𝗯
abbrev bsc 𝗰
abbrev bsd 𝗱
abbrev bse 𝗲
abbrev bsf 𝗳
abbrev bsg 𝗴
abbrev bsh 𝗵
abbrev bsi 𝗶
abbrev bsj 𝗷
abbrev bsk 𝗸
abbrev bsl 𝗹
abbrev bsm 𝗺
abbrev bsn 𝗻
abbrev bso 𝗼
abbrev bsp 𝗽
abbrev bsq 𝗾
abbrev bsr 𝗿
abbrev bss 𝘀
abbrev bst 𝘁
abbrev bsu 𝘂
abbrev bsv 𝘃
abbrev bsw 𝘄
abbrev bsx 𝘅
abbrev bsy 𝘆
abbrev bsz 𝘇
abbrev bs1 𝟬
abbrev bs2 𝟭
abbrev bs3 𝟮
abbrev bs4 𝟯
abbrev bs5 𝟰
abbrev bs6 𝟱
abbrev bs7 𝟲
abbrev bs8 𝟳
abbrev bs9 𝟴
abbrev bs10 𝟵
abbrev bsiA 𝘼
abbrev bsiB 𝘽
abbrev bsiC 𝘾
abbrev bsiD 𝘿
abbrev bsiE 𝙀
abbrev bsiF 𝙁
abbrev bsiG 𝙂
abbrev bsiH 𝙃
abbrev bsiI 𝙄
abbrev bsiJ 𝙅
abbrev bsiK 𝙆
abbrev bsiL 𝙇
abbrev bsiM 𝙈
abbrev bsiN 𝙉
abbrev bsiO 𝙊
abbrev bsiP 𝙋
abbrev bsiQ 𝙌
abbrev bsiR 𝙍
abbrev bsiS 𝙎
abbrev bsiT 𝙏
abbrev bsiU 𝙐
abbrev bsiV 𝙑
abbrev bsiW 𝙒
abbrev bsiX 𝙓
abbrev bsiY 𝙔
abbrev bsiZ 𝙕
abbrev bsia 𝙖
abbrev bsib 𝙗
abbrev bsic 𝙘
abbrev bsid 𝙙
abbrev bsie 𝙚
abbrev bsif 𝙛
abbrev bsig 𝙜
abbrev bsih 𝙝
abbrev bsii 𝙞
abbrev bsij 𝙟
abbrev bsik 𝙠
abbrev bsil 𝙡
abbrev bsim 𝙢
abbrev bsin 𝙣
abbrev bsio 𝙤
abbrev bsip 𝙥
abbrev bsiq 𝙦
abbrev bsir 𝙧
abbrev bsis 𝙨
abbrev bsit 𝙩
abbrev bsiu 𝙪
abbrev bsiv 𝙫
abbrev bsiw 𝙬
abbrev bsix 𝙭
abbrev bsiy 𝙮
abbrev bsiz 𝙯
abbrev bbA 𝔸
abbrev bbB 𝔹
abbrev bbC ℂ
abbrev bbD 𝔻
abbrev bbE 𝔼
abbrev bbF 𝔽
abbrev bbG 𝔾
abbrev bbH ℍ
abbrev bbI 𝕀
abbrev bbJ 𝕁
abbrev bbK 𝕂
abbrev bbL 𝕃
abbrev bbM 𝕄
abbrev bbN ℕ
abbrev bbO 𝕆
abbrev bbP ℙ
abbrev bbQ ℚ
abbrev bbR ℝ
abbrev bbS 𝕊
abbrev bbT 𝕋
abbrev bbU 𝕌
abbrev bbV 𝕍
abbrev bbW 𝕎
abbrev bbX 𝕏
abbrev bbY 𝕐
abbrev bbZ ℤ
abbrev bba 𝕒
abbrev bbb 𝕓
abbrev bbc 𝕔
abbrev bbd 𝕕
abbrev bbe 𝕖
abbrev bbf 𝕗
abbrev bbg 𝕘
abbrev bbh 𝕙
abbrev bbi 𝕚
abbrev bbj 𝕛
abbrev bbk 𝕜
abbrev bbl 𝕝
abbrev bbm 𝕞
abbrev bbn 𝕟
abbrev bbo 𝕠
abbrev bbp 𝕡
abbrev bbq 𝕢
abbrev bbr 𝕣
abbrev bbs 𝕤
abbrev bbt 𝕥
abbrev bbu 𝕦
abbrev bbv 𝕧
abbrev bbw 𝕨
abbrev bbx 𝕩
abbrev bby 𝕪
abbrev bbz 𝕫
abbrev bb1 𝟘
abbrev bb2 𝟙
abbrev bb3 𝟚
abbrev bb4 𝟛
abbrev bb5 𝟜
abbrev bb6 𝟝
abbrev bb7 𝟞
abbrev bb8 𝟟
abbrev bb9 𝟠
abbrev bb10 𝟡
abbrev bbiD ⅅ
abbrev bbid ⅆ
abbrev bbie ⅇ
abbrev bbii ⅈ
abbrev bbij ⅉ
abbrev bbGam ℾ
abbrev bbPi ℿ
abbrev bbSig ⅀
abbrev bbgam ℽ
abbrev bbpi ℼ
abbrev frakA 𝔄
abbrev frakB 𝔅
abbrev frakC ℭ
abbrev frakD 𝔇
abbrev frakE 𝔈
abbrev frakF 𝔉
abbrev frakG 𝔊
abbrev frakH ℌ
abbrev frakI ℑ
abbrev frakJ 𝔍
abbrev frakK 𝔎
abbrev frakL 𝔏
abbrev frakM 𝔐
abbrev frakN 𝔑
abbrev frakO 𝔒
abbrev frakP 𝔓
abbrev frakQ 𝔔
abbrev frakR ℜ
abbrev frakS 𝔖
abbrev frakT 𝔗
abbrev frakU 𝔘
abbrev frakV 𝔙
abbrev frakW 𝔚
abbrev frakX 𝔛
abbrev frakY 𝔜
abbrev frakZ ℨ
abbrev fraka 𝔞
abbrev frakb 𝔟
abbrev frakc 𝔠
abbrev frakd 𝔡
abbrev frake 𝔢
abbrev frakf 𝔣
abbrev frakg 𝔤
abbrev frakh 𝔥
abbrev fraki 𝔦
abbrev frakj 𝔧
abbrev frakk 𝔨
abbrev frakl 𝔩
abbrev frakm 𝔪
abbrev frakn 𝔫
abbrev frako 𝔬
abbrev frakp 𝔭
abbrev frakq 𝔮
abbrev frakr 𝔯
abbrev fraks 𝔰
abbrev frakt 𝔱
abbrev fraku 𝔲
abbrev frakv 𝔳
abbrev frakw 𝔴
abbrev frakx 𝔵
abbrev fraky 𝔶
abbrev frakz 𝔷
abbrev bfrakA 𝕬
abbrev bfrakB 𝕭
abbrev bfrakC 𝕮
abbrev bfrakD 𝕯
abbrev bfrakE 𝕰
abbrev bfrakF 𝕱
abbrev bfrakG 𝕲
abbrev bfrakH 𝕳
abbrev bfrakI 𝕴
abbrev bfrakJ 𝕵
abbrev bfrakK 𝕶
abbrev bfrakL 𝕷
abbrev bfrakM 𝕸
abbrev bfrakN 𝕹
abbrev bfrakO 𝕺
abbrev bfrakP 𝕻
abbrev bfrakQ 𝕼
abbrev bfrakR 𝕽
abbrev bfrakS 𝕾
abbrev bfrakT 𝕿
abbrev bfrakU 𝖀
abbrev bfrakV 𝖁
abbrev bfrakW 𝖂
abbrev bfrakX 𝖃
abbrev bfrakY 𝖄
abbrev bfrakZ 𝖅
abbrev bfraka 𝖆
abbrev bfrakb 𝖇
abbrev bfrakc 𝖈
abbrev bfrakd 𝖉
abbrev bfrake 𝖊
abbrev bfrakf 𝖋
abbrev bfrakg 𝖌
abbrev bfrakh 𝖍
abbrev bfraki 𝖎
abbrev bfrakj 𝖏
abbrev bfrakk 𝖐
abbrev bfrakl 𝖑
abbrev bfrakm 𝖒
abbrev bfrakn 𝖓
abbrev bfrako 𝖔
abbrev bfrakp 𝖕
abbrev bfrakq 𝖖
abbrev bfrakr 𝖗
abbrev bfraks 𝖘
abbrev bfrakt 𝖙
abbrev bfraku 𝖚
abbrev bfrakv 𝖛
abbrev bfrakw 𝖜
abbrev bfrakx 𝖝
abbrev bfraky 𝖞
abbrev bfrakz 𝖟
abbrev ^0 ⁰
abbrev ^1 ¹
abbrev ^2 ²
abbrev ^3 ³
abbrev ^4 ⁴
abbrev ^5 ⁵
abbrev ^6 ⁶
abbrev ^7 ⁷
abbrev ^8 ⁸
abbrev ^9 ⁹
abbrev ^+ ⁺
abbrev ^- ⁻
abbrev ^= ⁼
abbrev ^( ⁽
abbrev ^) ⁾
abbrev ^A ᴬ
abbrev ^B ᴮ
abbrev ^D ᴰ
abbrev ^E ᴱ
abbrev ^G ᴳ
abbrev ^H ᴴ
abbrev ^I ᴵ
abbrev ^J ᴶ
abbrev ^K ᴷ
abbrev ^L ᴸ
abbrev ^M ᴹ
abbrev ^N ᴺ
abbrev ^O ᴼ
abbrev ^P ᴾ
abbrev ^R ᴿ
abbrev ^T ᵀ
abbrev ^U ᵁ
abbrev ^V ⱽ
abbrev ^W ᵂ
abbrev ^a ᵃ
abbrev ^b ᵇ
abbrev ^c ᶜ
abbrev ^d ᵈ
abbrev ^e ᵉ
abbrev ^f ᶠ
abbrev ^g ᵍ
abbrev ^h ʰ
abbrev ^i ⁱ
abbrev ^j ʲ
abbrev ^k ᵏ
abbrev ^l ˡ
abbrev ^m ᵐ
abbrev ^n ⁿ
abbrev ^o ᵒ
abbrev ^p ᵖ
abbrev ^r ʳ
abbrev ^s ˢ
abbrev ^t ᵗ
abbrev ^u ᵘ
abbrev ^v ᵛ
abbrev ^w ʷ
abbrev ^x ˣ
abbrev ^y ʸ
abbrev ^z ᶻ
abbrev _1 ₀
abbrev _2 ₁
abbrev _3 ₂
abbrev _4 ₃
abbrev _5 ₄
abbrev _6 ₅
abbrev _7 ₆
abbrev _8 ₇
abbrev _9 ₈
abbrev _10 ₉
abbrev _+ ₊
abbrev _- ₋
abbrev _= ₌
abbrev _( ₍
abbrev _) ₎
abbrev _a ₐ
abbrev _e ₑ
abbrev _h ₕ
abbrev _i ᵢ
abbrev _j ⱼ
abbrev _k ₖ
abbrev _l ₗ
abbrev _m ₘ
abbrev _n ₙ
abbrev _o ₒ
abbrev _p ₚ
abbrev _r ᵣ
abbrev _s ₛ
abbrev _t ₜ
abbrev _u ᵤ
abbrev _v ᵥ
abbrev _x ₓ
abbrev blank ⠀
abbrev Alpha Α
abbrev Beta Β
abbrev Gamma Γ
abbrev Delta Δ
abbrev Epsilon Ε
abbrev Zeta Ζ
abbrev Eta Η
abbrev Theta Θ
abbrev Iota Ι
abbrev Kappa Κ
abbrev Lambda Λ
abbrev Mu Μ
abbrev Nu Ν
abbrev Xi Ξ
abbrev Omicron Ο
abbrev Pi Π
abbrev Rho Ρ
abbrev Sigma Σ
abbrev Tau Τ
abbrev Upsilon Υ
abbrev Phi Φ
abbrev Chi Χ
abbrev Psi Ψ
abbrev Omega Ω
abbrev alpha α
abbrev beta β
abbrev curbeta ϐ
abbrev gamma γ
abbrev delta δ
abbrev epsilon ε
abbrev lunepsilon ϵ
abbrev zeta ζ
abbrev eta η
abbrev theta ϑ
abbrev vtheta θ
abbrev iota ι
abbrev kappa κ
abbrev curkappa ϰ
abbrev lambda λ
abbrev mu μ
abbrev nu ν
abbrev xi ξ
abbrev omicron ο
abbrev pi π
abbrev curpi ϖ
abbrev rho ρ
abbrev currho ϱ
abbrev sigma σ
abbrev finsigma ς
abbrev tau τ
abbrev upsilon υ
abbrev phi φ
abbrev clophi ϕ
abbrev chi χ
abbrev psi ψ
abbrev omega ω
abbrev eur €
abbrev gbp £
abbrev usd $
abbrev yen ¥
abbrev brl R$
abbrev spc ␣
abbrev nbsp  
abbrev return ⏎
abbrev lqua ⌜
abbrev rqua ⌝
abbrev langle ⟨
abbrev rangle ⟩
abbrev lceil ⌈
abbrev rceil ⌉
abbrev lfloor ⌊
abbrev rfloor ⌋
abbrev lbag ⟅
abbrev rbag ⟆
abbrev lsem ⟦
abbrev rsem ⟧
abbrev lSet ⦃
abbrev rSet ⦄
abbrev lPar ⦅
abbrev rPar ⦆
abbrev lban ⦇
abbrev rban ⦈
abbrev lAngle ⦉
abbrev rAngle ⦊
abbrev lnorm ‖
abbrev rnorm ‖
abbrev halmos ∎
abbrev qed ∎
abbrev leq ≤
abbrev geq ≥
abbrev neq ≠
abbrev nlt ≮
abbrev ngt ≯
abbrev nleq ≰
abbrev ngeq ≱
abbrev div ∣
abbrev ndiv ∤
abbrev forall ∀
abbrev exists ∃
abbrev nexists ∄
abbrev implies ⇒
abbrev implied ⇐
abbrev iff ⇔
abbrev timplies ⟹
abbrev timplied ⟸
abbrev tiff ⟺
abbrev vimplies ⇓
abbrev vimplied ⇑
abbrev viff ⇕
abbrev rlarr ⇄
abbrev lrarr ⇆
abbrev tofrom ⇄
abbrev fromto ⇆
abbrev udarr ⇅
abbrev uuarr ⇈
abbrev ddarr ⇊
abbrev llarr ⇇
abbrev rrarr ⇉
abbrev uarr ↑
abbrev darr ↓
abbrev larr ←
abbrev rarr →
abbrev nimplied ⇍
abbrev nimplies ⇏
abbrev niff ⇎
abbrev inteq ≡
abbrev intneq ≢
abbrev defeq ≝
abbrev doteq ≐
abbrev askeq ≟
abbrev asteq ⩮
abbrev stareq ≛
abbrev defiff ⇐≝⇒
abbrev intiff ⇚⇛
abbrev intimplies ⇛
abbrev vintimplied ⤊
abbrev vintimplies ⤋
abbrev intimplied ⇚
abbrev ledfrom ↜
abbrev leadsto ↝
abbrev rleads ↝
abbrev lleads ↜
abbrev eqto ⥱
abbrev isoto ⥲
abbrev Funto ⥤
abbrev therefore ∴
abbrev because ∵
abbrev vdots ⋮
abbrev hdots ⋯
abbrev cdots ⋯
abbrev dotsb ⋯
abbrev ldots …
abbrev dotsc …
abbrev pm ±
abbrev mp ∓
abbrev infty ∞
abbrev pinfty +∞
abbrev minfty -∞
abbrev pminfty ±∞
abbrev mpinfty ∓∞
abbrev surd √
abbrev integ ∫
abbrev iinteg ∬
abbrev iiinteg ∭
abbrev ointeg ∮
abbrev nabla ∇
abbrev partial ∂
abbrev ast ∗
abbrev star ⋆
abbrev bullet ∙
abbrev cdot ·
abbrev ntimes ·
abbrev cross ×
abbrev times ×
abbrev circ ∘
abbrev oplus ⊕
abbrev ominus ⊖
abbrev otimes ⊗
abbrev tensor ⊗
abbrev ocross ⊗
abbrev odiv ⊘
abbrev odot ⊙
abbrev dotminus ∸
abbrev dotplus ⨢
abbrev monus ∸
abbrev dottimes ⨰
abbrev uplus ⊎
abbrev Uplus ⨄
abbrev dhole –
abbrev hole _
abbrev emptyset Ø
abbrev empty Ø
abbrev bools 𝔹
abbrev nats ℕ
abbrev ints ℤ
abbrev rats ℚ
abbrev reals ℝ
abbrev complex ℂ
abbrev in ∈
abbrev notin ∉
abbrev nin ∉
abbrev ni ∋
abbrev notni ∌
abbrev nni ∌
abbrev Inter ⋂
abbrev Union ⋃
abbrev inter ∩
abbrev union ∪
abbrev disjunion ⊎
abbrev Disjunion ⨄
abbrev dunion ⊎
abbrev Dunion ⨄
abbrev symdiff ∆
abbrev sdiff ∆
abbrev setminus ∖
abbrev minus ∖
abbrev subset ⊆
abbrev supset ⊇
abbrev psubset ⊊
abbrev psupset ⊋
abbrev hsubset ⊂
abbrev hsupset ⊃
abbrev nsubset ⊈
abbrev nsupset ⊉
abbrev subsetneq ⊊
abbrev supsetneq ⊋
abbrev sqleq ⊑
abbrev sqgeq ⊒
abbrev sqlt ⊏
abbrev sqgt ⊐
abbrev sqlneq ⋤
abbrev sqgneq ⋥
abbrev sqnleq ⋢
abbrev sqngeq ⋣
abbrev semleq ⊑
abbrev semgeq ⊒
abbrev semlneq ⋤
abbrev semgneq ⋥
abbrev nsemleq ⋢
abbrev nsemgeq ⋣
abbrev domleq ⊑
abbrev domgeq ⊒
abbrev domlneq ⋤
abbrev domgneq ⋥
abbrev pset ℘
abbrev aleph ℵ
abbrev beth ℶ
abbrev gimel ℷ
abbrev comp ∘
abbrev to →
abbrev from ←
abbrev nto ↛
abbrev nfrom ↚
abbrev parto ⇀
abbrev mapsto ↦
abbrev mapsfrom ↤
abbrev tmapsto ⟼
abbrev tmapsfrom ⟻
abbrev mapsup ↥
abbrev mapsdown ↧
abbrev parfrom ↼
abbrev rest ↾
abbrev surto ↠
abbrev surfrom ↞
abbrev injto ↣
abbrev injfrom ↢
abbrev embto ↪
abbrev embfrom ↩
abbrev bijto ⤖
abbrev relto ⇾
abbrev relfrom ⇽
abbrev dual ∂
abbrev ndetfrom ⇜
abbrev ndetto ⇝
abbrev dfrom ⇠
abbrev dto ⇢
abbrev equiv ≅
abbrev nequiv ≇
abbrev iso ≅
abbrev niso ≇
abbrev rcomp ⋄
abbrev cong ≡
abbrev ncong ≢
abbrev normal ⊴
abbrev pnormal ⊲
abbrev sim ~
abbrev nsim ≁
abbrev approx ≈
abbrev napprox ≉
abbrev Prod ∏
abbrev Coprod ∐
abbrev coprod ⨿
abbrev Sum ∑
abbrev op ᵒᵖ
abbrev concat ⧺
abbrev inv ⁻¹
abbrev lnot ¬
abbrev lforall ∀
abbrev lexists ∃
abbrev limplies →
abbrev limplied ←
abbrev liff ↔
abbrev land ∧
abbrev lor ∨
abbrev Land ⋀
abbrev Lor ⋁
abbrev sequent ⊢
abbrev proves ⊢
abbrev nproves ⊬
abbrev models ⊨
abbrev nmodels ⊭
abbrev forces ⊩
abbrev nforces ⊮
abbrev linnot ⊥
abbrev linto ⊸
abbrev linwith &
abbrev linpar ⅋
abbrev himplies ⥰
abbrev horse ⥰
abbrev top ⊤
abbrev bottom ⊥
abbrev Meet ⋀
abbrev Join ⋁
abbrev meet ∧
abbrev join ∨
abbrev incompar ≸
abbrev incompat ‖
abbrev wbelow ≪
abbrev wabove ≫
abbrev domlt ⊏
abbrev domgt ⊐
abbrev domleq ⊑
abbrev domgeq ⊒
abbrev glb ⊓
abbrev lub ⊔
abbrev Glb ⨅
abbrev Lub ⨆
abbrev spades ♠
abbrev hearts ♡
abbrev diamonds ♢
abbrev clubs ♣
abbrev magic ⛤
abbrev rturnstile ⊢
abbrev lturnstile ⊣
abbrev sqleftarrow ⇜
abbrev sqrightarrow ⇝
abbrev sqbotharrow ↭
abbrev nwarrow ↖
abbrev nearrow ↗
abbrev swarrow ↙
abbrev searrow ↘
abbrev duparrow ⇡
abbrev drightarrow ⇢
abbrev ddownarrow ⇣
abbrev dleftarrow ⇠
abbrev up ↑
abbrev down ↓
abbrev left ←
abbrev right →
abbrev Ell ℒ
abbrev ell ℓ
abbrev bang !
abbrev gnab ¡
abbrev bbang ‼
abbrev ibang ‽
abbrev ignab ⸘
abbrev abang ⁈
abbrev bask ⁉
abbrev frown ⌢
abbrev smile ⌣
abbrev utri △
abbrev dtri ▽
abbrev ltri ◁
abbrev rtri ▷
abbrev utris ▵
abbrev dtris ▿
abbrev ltris ◃
abbrev rtris ▹
abbrev ubtri ▲
abbrev dbtri ▼
abbrev lbtri ◄
abbrev rbtri ►
abbrev ubtris ▴
abbrev dbtris ▾
abbrev lbtris ◂
abbrev rbtris ▸
abbrev CAT 𝐂𝐚𝐭
abbrev SET 𝐒𝐞𝐭
abbrev PSET 𝐏𝐒𝐞𝐭
abbrev PTDSET 𝐏𝐭𝐝𝐒𝐞𝐭
abbrev FINSET 𝐅𝐢𝐧𝐒𝐞𝐭
abbrev FINORD 𝐅𝐢𝐧𝐎𝐫𝐝
abbrev ORD 𝐎𝐫𝐝
abbrev PROSET 𝐏𝐫𝐨𝐬𝐞𝐭
abbrev POSET 𝐏𝐨𝐬𝐞𝐭
abbrev SGROUP 𝐒𝐞𝐦𝐢𝐠𝐫𝐨𝐮𝐩
abbrev SGRP 𝐒𝐞𝐦𝐢𝐠𝐫𝐩
abbrev MON 𝐌𝐨𝐧
abbrev MONOID 𝐌𝐨𝐧𝐨𝐢𝐝
abbrev GROUP 𝐆𝐫𝐨𝐮𝐩
abbrev GRP 𝐆𝐫𝐩
abbrev ABEL 𝐀𝐛𝐞𝐥
abbrev RING 𝐑𝐢𝐧𝐠
abbrev RNG 𝐑𝐧𝐠
abbrev RIG 𝐑𝐢𝐠
abbrev MOD 𝐌𝐨𝐝
abbrev MAT 𝐌𝐚𝐭𝐫𝐢𝐱
abbrev LAT 𝐋𝐚𝐭𝐭𝐢𝐜𝐞
abbrev HALG 𝐇𝐞𝐲𝐭𝐢𝐧𝐠
abbrev BALG 𝐁𝐨𝐨𝐥𝐞𝐚𝐧
abbrev HA 𝐇𝐀
abbrev BA 𝐁𝐀
abbrev MODEL 𝐌𝐨𝐝𝐞𝐥
abbrev psubs ⊊
abbrev psups ⊋
abbrev hsubs ⊂
abbrev hsups ⊃
abbrev nsubs ⊈
abbrev nsups ⊉
abbrev subsne ⊊
abbrev supsne ⊋
abbrev fa ∀
abbrev ex ∃
abbrev nex ∄
abbrev imps ⇒
abbrev impd ⇐
abbrev iff ⇔
abbrev timps ⟹
abbrev timpd ⟸
abbrev tiff ⟺
abbrev vimps ⇓
abbrev vimpd ⇑
abbrev nimpd ⇍
abbrev nimps ⇏
abbrev rmaps ↦
abbrev lmaps ↤
abbrev Rmaps ⟼
abbrev Lmaps ⟻
abbrev there ∴
abbrev cause ∵
abbrev dplus ⨢
abbrev dtimes ⨰
